<a href="https://colab.research.google.com/github/sijojoy186/LearnPython/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas


In [19]:
dic1 = {'cust1':[22,'pune',1], 'cust2':[23,'delhi',0],
     'cust3':[25,'kolkota',1]}
dic1

{'cust1': [22, 'pune', 1],
 'cust2': [23, 'delhi', 0],
 'cust3': [25, 'kolkota', 1]}

In [20]:
import pandas as pd

df = pd.DataFrame(dic1)
df

cust1  cust2    cust3
0    22     23       25
1  pune  delhi  kolkota
2     1      0        1

In [23]:
dict2 = {
    'cust_id': ['c1','c2','c3'],
    'cred_score': [700,750,690],
    'age': [25,28,30],
    'debt_status':[1,0,0]
}

df2 =pd.DataFrame(dict2)

df2

dict2



{'cust_id': ['c1', 'c2', 'c3'],
 'cred_score': [700, 750, 690],
 'age': [25, 28, 30],
 'debt_status': [1, 0, 0]}

In [25]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   cust_id      3 non-null      object
 1   cred_score   3 non-null      int64 
 2   age          3 non-null      int64 
 3   debt_status  3 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 228.0+ bytes


In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   cust1   3 non-null      object
 1   cust2   3 non-null      object
 2   cust3   3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes


In [27]:
df.describe()

cust1  cust2  cust3
count       3      3      3
unique      3      3      3
top        22     23     25
freq        1      1      1

In [28]:
df2.describe()

cred_score        age  debt_status
count    3.000000   3.000000     3.000000
mean   713.333333  27.666667     0.333333
std     32.145503   2.516611     0.577350
min    690.000000  25.000000     0.000000
25%    695.000000  26.500000     0.000000
50%    700.000000  28.000000     0.000000
75%    725.000000  29.000000     0.500000
max    750.000000  30.000000     1.000000

In [31]:
import numpy as np

sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


In [32]:
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [33]:
m = np.eye(5)
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
vec = np.arange(10, 20, 3)
print(vec)

[10 13 16 19]


In [35]:
vec = np.linspace(10,20,3)
print(vec)


[10. 15. 20.]


In [37]:
vec = np.zeros([2,3])
print(vec)

[[0. 0. 0.]
 [0. 0. 0.]]


In [39]:
vec = np.arange(0,6)
print(vec.reshape((2,3)))

[[0 1 2]
 [3 4 5]]
